In [1]:
import pickle

In [2]:
import pandas as pd
import numpy as np

In [3]:
import spacy

nlp = spacy.load('en_core_web_sm')

In [4]:
with open(r"D:\data\openparliament\models\vocab_dict_large.pkl", "rb") as f:
    vocab_count_dict = pickle.load(f)

In [5]:
max_vocab = 0
max_s = None
for k, v in vocab_count_dict.items():
    if len(vocab_count_dict[k])>max_vocab:
        max_vocab = len(v)
        max_s = k

In [6]:
max_s

177

In [7]:
list(vocab_count_dict.keys())[:10]

[3465, 173, 43, 216, 256, 4458, 131, 3899, 96, 14]

In [8]:
len(vocab_count_dict[4458])

4356

In [9]:
vocab_count_dict[96]

{'dangerously',
 'conventional',
 'genie',
 'welcome',
 'squadron',
 'hooked',
 'clow',
 'bad',
 'shipper',
 'repeatedly',
 'impression',
 'exempt',
 'whisky',
 'blindside',
 'crossing',
 'humourous',
 'editor',
 'dip',
 'exhibition',
 'doctrine',
 'flap',
 'intend',
 'tuck',
 'revolt',
 'late',
 'country',
 'teenage',
 'mill',
 'background',
 'dissimilar',
 'harsh',
 'chemical',
 'garry',
 'empathize',
 'acknowledge',
 'iconic',
 'bribery',
 'restructure',
 'farmer',
 'z',
 'belatedly',
 'stop',
 'gasoline',
 'unusual',
 'supercluster',
 'borrow',
 'punishment',
 'junior',
 'lob',
 'butter',
 'curtail',
 'get',
 'monetary',
 'retract',
 'prop',
 'impeccable',
 'overjoy',
 'presume',
 'avant',
 'vacancy',
 'buddy',
 'hasty',
 'rehash',
 'adapt',
 'mactaquac',
 'undo',
 'rebuild',
 'fine',
 'survival',
 'dfc',
 'outstanding',
 'necessity',
 'deter',
 'equitable',
 'imprison',
 'intern',
 'caregive',
 'plight',
 'clearly',
 'lax',
 'deficiency',
 'amateur',
 'potential',
 'insertion',
 '

In [10]:
sentence = nlp("This probably had understated problems with understatements")

In [11]:
for token in sentence:
    print(token.lemma_)

this
probably
have
understate
problem
with
understatement


In [12]:
v_set = set()

In [13]:
for k, v in vocab_count_dict.items():
    v_set.update(v)

In [14]:
len(v_set)

68464

In [15]:
di = dict.fromkeys(v_set, [1])

In [16]:
fake = [1]*68464

In [17]:
di = {'word1': fake}

In [18]:
df = pd.DataFrame(di)

In [19]:
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))

In [20]:
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'))

In [21]:
df.append(df2, ignore_index=True)

A  B
0  1  2
1  3  4
2  5  6
3  7  8

In [22]:
df = pd.DataFrame({'member_id': list(vocab_count_dict.keys())})

In [23]:
df.head()

member_id
0       3465
1        173
2         43
3        216
4        256

In [24]:
v1_set = vocab_count_dict[96]

In [25]:
type(v1_set)

set

In [26]:
v_set == v1_set

False

In [27]:
v = list(v_set)

In [28]:
v.sort()

In [29]:
v[590]

'97b'

##### from PyDictionary import PyDictionary
dictionary=PyDictionary()

In [30]:
any(char.isdigit() for char in 'sdb')

False

In [31]:
any(char.isdigit() for char in '97b')

True

In [32]:
a = [1,2,3,4]

In [33]:
b = [4]

In [34]:
np.in1d(a,b)

array([False, False, False,  True])

In [35]:
v_in= np.in1d(list(v_set), list(v1_set))

In [36]:
v_in = v_in.astype(int)

In [37]:
sum(v_in)

8443

In [38]:
def wordset_to_1(member_id):
    m_vocab = vocab_count_dict[member_id]
    v_in= np.in1d(list(v_set), list(m_vocab))
    v_in = v_in.astype(int)
    df[memb]

In [39]:
list(v_set)[:10]

['uncleared',
 'cosmogonic',
 'conventional',
 'incorrigibility',
 'photocopied',
 'meticulon',
 'sikaran',
 'advising',
 'blueblood',
 'carbohydrate']

In [40]:
words = list(v_set)

In [41]:
words.sort()

In [42]:
words[800:810]

['abridge',
 'abridged',
 'abridgement',
 'abridgment',
 'abroad',
 'abrogate',
 'abrogating',
 'abrogation',
 'abrupt',
 'abruption']

In [44]:
df = pd.DataFrame(columns = newcols)

In [45]:
newcols[-10:]

['über',
 'überminister',
 'œuvrant',
 'ᖁᔭᓐᓇᒦᒃ',
 '’',
 '“',
 '”',
 '•',
 '•support',
 '€']

In [46]:
s = newcols[-9]

In [47]:
s

'überminister'

In [48]:
s.encode("ascii", "ignore")

b'berminister'

In [49]:
w = newcols[-7]

In [50]:
len(w.encode("latin-1",'ignore'))

0

In [51]:
len(w)

6

if the length of the original non-latinate token is nonzero and the length of the latin-1-encoded token is zero, it it can't be represented using the latin character set #TODO later - unidecode tokens

In [52]:
from unidecode import unidecode

In [53]:
unidecode(s) 

'uberminister'

In [54]:
sa = set()
sb = set()

In [55]:
sa.update([1,2,3,4])
sb.update([2,5])

In [56]:
[x in sb for x in sa]

[False, True, False, False]

In [66]:
my_dict = {'96': list(v1_set), 'vocab': list(v_set)}

In [67]:
df = pd.DataFrame.from_dict(my_dict, orient='index')

In [68]:
df.head()

0             1             2                3            4      \
96     dangerously  conventional         genie          welcome     squadron   
vocab    uncleared    cosmogonic  conventional  incorrigibility  photocopied   

           5        6         7          8             9      ...   68454  \
96        hooked     clow       bad    shipper    repeatedly  ...    None   
vocab  meticulon  sikaran  advising  blueblood  carbohydrate  ...  fizzle   

       68455     68456  68457      68458  68459      68460 68461 68462  \
96      None      None   None       None   None       None  None  None   
vocab  hulse  outlying  pluto  enviously  tunic  genuinely  saab  iowu   

             68463  
96            None  
vocab  bloodstaine  

[2 rows x 68464 columns]

how to do this: 

    - make binary columns per sorted word
    - make a dictionary with the key as the member id, and the values as the np array
    - turn to dict
    - transpose
    - turn the index into a column, replace column names with old index values + v_set

In [69]:
v_in= np.in1d(list(v_set), list(v1_set))

In [70]:
v_in[:10]

array([False, False,  True, False, False, False, False, False, False,
       False])

In [84]:
vocab_df = dict()

In [89]:
%%time
for k, v in vocab_count_dict.items():
    vocab_df[k] = np.in1d(list(v_set), list(v)).astype(int)

Wall time: 56.1 s


In [90]:
print('done')

done


In [91]:
vocab_df[96]

array([0, 0, 1, ..., 0, 0, 0])

In [92]:
df = pd.DataFrame.from_dict(vocab_df)

In [96]:
#transpose
df = df.transpose() 

In [97]:
df.head()

0      1      2      3      4      5      6      7      8      9      \
3465      0      0      0      0      0      0      0      0      0      0   
173       0      0      1      0      0      0      0      0      0      0   
43        0      0      1      0      0      0      0      0      0      0   
216       0      0      1      0      0      0      0      0      0      0   
256       0      0      0      0      0      0      0      0      0      0   

      ...  68454  68455  68456  68457  68458  68459  68460  68461  68462  \
3465  ...      0      0      0      0      0      0      0      0      0   
173   ...      0      0      1      0      0      0      1      0      0   
43    ...      0      0      0      0      0      0      1      0      0   
216   ...      0      0      0      0      0      0      1      0      0   
256   ...      0      0      0      0      0      0      1      0      0   

      68463  
3465      0  
173       0  
43        0  
216       0  
256       0  

[5 rows x 68464 columns]

In [98]:
df['member_id'] = df.index

In [100]:
df.shape

(1051, 68465)

In [102]:
df.reset_index(level=None, drop=False, inplace=True)

In [106]:
df.drop(['member_id'], axis=1, inplace=True)

In [107]:
df = df.rename({'index': 'member_id'},axis=1 )

In [108]:
df.head()

member_id  0  1  2  3  4  5  6  7  8  ...  68454  68455  68456  68457  \
0       3465  0  0  0  0  0  0  0  0  0  ...      0      0      0      0   
1        173  0  0  1  0  0  0  0  0  0  ...      0      0      1      0   
2         43  0  0  1  0  0  0  0  0  0  ...      0      0      0      0   
3        216  0  0  1  0  0  0  0  0  0  ...      0      0      0      0   
4        256  0  0  0  0  0  0  0  0  0  ...      0      0      0      0   

   68458  68459  68460  68461  68462  68463  
0      0      0      0      0      0      0  
1      0      0      1      0      0      0  
2      0      0      1      0      0      0  
3      0      0      1      0      0      0  
4      0      0      1      0      0      0  

[5 rows x 68465 columns]

In [109]:
newcols = ['member_id'] + words

In [112]:
df.columns = [unidecode(x) for x in newcols]

In [113]:
df.head()

member_id                                                                 \
0       3465  0   0    0     0      0       0        0         0          0   
1        173  0   0    1     0      0       0        0         0          0   
2         43  0   0    1     0      0       0        0         0          0   
3        216  0   0    1     0      0       0        0         0          0   
4        256  0   0    0     0      0       0        0         0          0   

   ...  uber  uberminister  oeuvrant  qoyannamiik  '  "  "  *  *support  EUR  
0  ...     0             0         0            0  0  0  0  0         0    0  
1  ...     0             0         1            0  0  0  1  0         0    0  
2  ...     0             0         0            0  0  0  1  0         0    0  
3  ...     0             0         0            0  0  0  1  0         0    0  
4  ...     0             0         0            0  0  0  1  0         0    0  

[5 rows x 68465 columns]

In [115]:
df.to_csv(r"D:\data\openparliament\vocab_count_df")

In [116]:
df_sums = df.drop(['member_id'], axis=1).sum(axis=1)

In [117]:
df_sums.head()

0    3037
1    6473
2    6468
3    7052
4    6184
dtype: int64